// ReportableConditions.swift
// Curated reference DB of US/global notifiable conditions used by the
// agent's lookup_reportable_conditions tool (Tier 4 — RAG over CDC NNDSS
// + WHO IDSR). Mirrors apps/mobile/convert/reportable_conditions.json;
// keep them in sync, the Python file is the bench-tested ground truth.
//
// Inlined as Swift static let so we don't have to register a JSON
// resource in the Xcode project (same pattern as LookupTable.swift).

import Foundation

struct ReportableCondition {
    let code: String
    let system: String
    let display: String
    let altNames: [String]
    let category: String?
    let source: String
    let sourceURL: String
}

enum ReportableConditions {
    static let primarySources = [
        "CDC National Notifiable Diseases Surveillance System (NNDSS) — https://ndc.services.cdc.gov/conditions/",
        "CDC eRSD reportable condition trigger codes — https://github.com/HL7/fhir-us-ecr",
        "WHO Integrated Disease Surveillance and Response (IDSR) — https://www.afro.who.int/health-topics/integrated-disease-surveillance",
    ]

    static let all: [ReportableCondition] = [
        ReportableCondition(code: "76272004",  system: "SNOMED", display: "Syphilis",                                          altNames: ["syphilis", "treponemal infection", "lues"],                                                                            category: "stis",                  source: "CDC NNDSS", sourceURL: "https://ndc.services.cdc.gov/conditions/syphilis/"),
        ReportableCondition(code: "186946009", system: "SNOMED", display: "Plasmodium malariae malaria",                       altNames: ["malaria", "Plasmodium infection", "P. malariae"],                                                                       category: "vector_borne",          source: "CDC NNDSS", sourceURL: "https://ndc.services.cdc.gov/conditions/malaria/"),
        ReportableCondition(code: "27836007",  system: "SNOMED", display: "Pertussis",                                         altNames: ["pertussis", "whooping cough", "Bordetella pertussis"],                                                                  category: "vaccine_preventable",   source: "CDC NNDSS", sourceURL: "https://ndc.services.cdc.gov/conditions/pertussis/"),
        ReportableCondition(code: "14189004",  system: "SNOMED", display: "Measles",                                           altNames: ["measles", "rubeola", "morbilli"],                                                                                       category: "vaccine_preventable",   source: "CDC NNDSS", sourceURL: "https://ndc.services.cdc.gov/conditions/measles/"),
        ReportableCondition(code: "36989005",  system: "SNOMED", display: "Mumps",                                             altNames: ["mumps", "epidemic parotitis"],                                                                                          category: "vaccine_preventable",   source: "CDC NNDSS", sourceURL: "https://ndc.services.cdc.gov/conditions/mumps/"),
        ReportableCondition(code: "36653000",  system: "SNOMED", display: "Rubella",                                           altNames: ["rubella", "German measles", "three-day measles"],                                                                       category: "vaccine_preventable",   source: "CDC NNDSS", sourceURL: "https://ndc.services.cdc.gov/conditions/rubella/"),
        ReportableCondition(code: "397428000", system: "SNOMED", display: "Diphtheria",                                        altNames: ["diphtheria", "Corynebacterium diphtheriae infection"],                                                                  category: "vaccine_preventable",   source: "CDC NNDSS", sourceURL: "https://ndc.services.cdc.gov/conditions/diphtheria/"),
        ReportableCondition(code: "76902006",  system: "SNOMED", display: "Tetanus",                                           altNames: ["tetanus", "lockjaw", "Clostridium tetani infection"],                                                                   category: "vaccine_preventable",   source: "CDC NNDSS", sourceURL: "https://ndc.services.cdc.gov/conditions/tetanus/"),
        ReportableCondition(code: "75702008",  system: "SNOMED", display: "Brucellosis",                                       altNames: ["brucellosis", "Malta fever", "undulant fever", "Brucella infection"],                                                   category: "zoonotic",              source: "CDC NNDSS", sourceURL: "https://ndc.services.cdc.gov/conditions/brucellosis/"),
        ReportableCondition(code: "1857005",   system: "SNOMED", display: "Cholera",                                           altNames: ["cholera", "Vibrio cholerae infection"],                                                                                 category: "outbreak_priority",     source: "WHO IDSR",  sourceURL: "https://www.afro.who.int/health-topics/cholera"),
        ReportableCondition(code: "37109004",  system: "SNOMED", display: "West Nile virus infection",                         altNames: ["West Nile", "WNV", "West Nile fever"],                                                                                  category: "vector_borne",          source: "CDC NNDSS", sourceURL: "https://ndc.services.cdc.gov/conditions/west-nile-virus/"),
        ReportableCondition(code: "111811007", system: "SNOMED", display: "Eastern equine encephalitis virus infection",      altNames: ["EEE", "eastern equine encephalitis", "Triple E"],                                                                       category: "vector_borne",          source: "CDC NNDSS", sourceURL: "https://ndc.services.cdc.gov/conditions/eastern-equine-encephalitis/"),
        ReportableCondition(code: "240589008", system: "SNOMED", display: "Chlamydia trachomatis infection",                   altNames: ["chlamydia", "Chlamydia trachomatis", "C. trachomatis"],                                                                 category: "stis",                  source: "CDC NNDSS", sourceURL: "https://ndc.services.cdc.gov/conditions/chlamydia-trachomatis-infection/"),
        ReportableCondition(code: "15628003",  system: "SNOMED", display: "Gonorrhea",                                         altNames: ["gonorrhea", "gonococcal infection", "Neisseria gonorrhoeae", "GC"],                                                     category: "stis",                  source: "CDC NNDSS", sourceURL: "https://ndc.services.cdc.gov/conditions/gonorrhea/"),
        ReportableCondition(code: "186431008", system: "SNOMED", display: "Clostridioides difficile infection",                altNames: ["C. diff", "C diff", "C difficile colitis", "Clostridioides difficile"],                                                 category: "healthcare_associated", source: "CDC NNDSS", sourceURL: "https://ndc.services.cdc.gov/conditions/clostridium-difficile-infection/"),
        ReportableCondition(code: "240370009", system: "SNOMED", display: "Methicillin-resistant Staphylococcus aureus infection", altNames: ["MRSA", "methicillin resistant Staph"],                                                                            category: "healthcare_associated", source: "CDC NNDSS", sourceURL: "https://ndc.services.cdc.gov/conditions/methicillin-resistant-staphylococcus-aureus/"),
        ReportableCondition(code: "47523006",  system: "SNOMED", display: "Carbapenem-resistant Enterobacteriaceae infection", altNames: ["CRE", "carbapenem-resistant Enterobacteriaceae"],                                                                       category: "healthcare_associated", source: "CDC NNDSS", sourceURL: "https://ndc.services.cdc.gov/conditions/carbapenem-resistant-enterobacteriaceae/"),
        ReportableCondition(code: "186150001", system: "SNOMED", display: "Q fever",                                           altNames: ["Q fever", "Coxiella burnetii infection"],                                                                               category: "zoonotic",              source: "CDC NNDSS", sourceURL: "https://ndc.services.cdc.gov/conditions/q-fever/"),
        ReportableCondition(code: "57124009",  system: "SNOMED", display: "Anthrax",                                           altNames: ["anthrax", "Bacillus anthracis infection", "woolsorter disease"],                                                        category: "select_agent",          source: "CDC NNDSS", sourceURL: "https://ndc.services.cdc.gov/conditions/anthrax/"),
        ReportableCondition(code: "58750007",  system: "SNOMED", display: "Plague",                                            altNames: ["plague", "Yersinia pestis infection", "bubonic plague"],                                                                category: "select_agent",          source: "CDC NNDSS", sourceURL: "https://ndc.services.cdc.gov/conditions/plague/"),
        ReportableCondition(code: "16541001",  system: "SNOMED", display: "Yellow fever",                                      altNames: ["yellow fever", "yellow fever virus infection"],                                                                         category: "vector_borne",          source: "WHO IDSR",  sourceURL: "https://www.afro.who.int/health-topics/yellow-fever"),
        ReportableCondition(code: "37796009",  system: "SNOMED", display: "Tularemia",                                         altNames: ["tularemia", "rabbit fever", "Francisella tularensis infection"],                                                        category: "zoonotic",              source: "CDC NNDSS", sourceURL: "https://ndc.services.cdc.gov/conditions/tularemia/"),
        ReportableCondition(code: "1851005",   system: "SNOMED", display: "Listeriosis",                                       altNames: ["listeriosis", "Listeria monocytogenes infection"],                                                                      category: "foodborne",             source: "CDC NNDSS", sourceURL: "https://ndc.services.cdc.gov/conditions/listeriosis/"),
        ReportableCondition(code: "302229004", system: "SNOMED", display: "Salmonellosis",                                     altNames: ["salmonellosis", "Salmonella infection", "salmonella enteritis"],                                                        category: "foodborne",             source: "CDC NNDSS", sourceURL: "https://ndc.services.cdc.gov/conditions/salmonellosis/"),
        ReportableCondition(code: "302231008", system: "SNOMED", display: "Shigellosis",                                       altNames: ["shigellosis", "Shigella infection", "bacillary dysentery"],                                                             category: "foodborne",             source: "CDC NNDSS", sourceURL: "https://ndc.services.cdc.gov/conditions/shigellosis/"),
        ReportableCondition(code: "84094009",  system: "SNOMED", display: "Rabies",                                            altNames: ["rabies", "hydrophobia", "lyssa"],                                                                                       category: "zoonotic",              source: "CDC NNDSS", sourceURL: "https://ndc.services.cdc.gov/conditions/rabies/"),
        ReportableCondition(code: "37436014",  system: "SNOMED", display: "Coccidioidomycosis",                                altNames: ["coccidioidomycosis", "valley fever", "Cocci", "San Joaquin Valley fever"],                                              category: "fungal",                source: "CDC NNDSS", sourceURL: "https://ndc.services.cdc.gov/conditions/coccidioidomycosis/"),
        ReportableCondition(code: "187192000", system: "SNOMED", display: "Histoplasmosis",                                    altNames: ["histoplasmosis", "Histoplasma capsulatum infection"],                                                                   category: "fungal",                source: "CDC NNDSS", sourceURL: "https://ndc.services.cdc.gov/conditions/histoplasmosis/"),
        ReportableCondition(code: "75116005",  system: "SNOMED", display: "Cryptosporidiosis",                                 altNames: ["cryptosporidiosis", "Cryptosporidium infection", "Crypto"],                                                             category: "foodborne",             source: "CDC NNDSS", sourceURL: "https://ndc.services.cdc.gov/conditions/cryptosporidiosis/"),
        ReportableCondition(code: "414488002", system: "SNOMED", display: "Ehrlichiosis",                                      altNames: ["ehrlichiosis", "human monocytic ehrlichiosis", "HME"],                                                                  category: "vector_borne",          source: "CDC NNDSS", sourceURL: "https://ndc.services.cdc.gov/conditions/ehrlichiosis/"),
        ReportableCondition(code: "186788009", system: "SNOMED", display: "Spotted fever rickettsiosis",                       altNames: ["Rocky Mountain spotted fever", "RMSF", "Rickettsia rickettsii", "spotted fever"],                                      category: "vector_borne",          source: "CDC NNDSS", sourceURL: "https://ndc.services.cdc.gov/conditions/spotted-fever-rickettsiosis/"),
        ReportableCondition(code: "10629511000119102", system: "SNOMED", display: "Babesiosis",                                altNames: ["babesiosis", "Babesia infection", "Babesia microti"],                                                                   category: "vector_borne",          source: "CDC NNDSS", sourceURL: "https://ndc.services.cdc.gov/conditions/babesiosis/"),
        ReportableCondition(code: "417093003", system: "SNOMED", display: "Powassan virus encephalitis",                       altNames: ["Powassan", "POWV", "Powassan encephalitis"],                                                                            category: "vector_borne",          source: "CDC NNDSS", sourceURL: "https://ndc.services.cdc.gov/conditions/powassan-virus-disease/"),
        ReportableCondition(code: "418182000", system: "SNOMED", display: "Chikungunya fever",                                 altNames: ["chikungunya", "CHIKV"],                                                                                                  category: "vector_borne",          source: "CDC NNDSS", sourceURL: "https://ndc.services.cdc.gov/conditions/chikungunya/"),
        ReportableCondition(code: "428175000", system: "SNOMED", display: "Hantavirus pulmonary syndrome",                     altNames: ["hantavirus", "HPS", "hantavirus pulmonary syndrome"],                                                                   category: "zoonotic",              source: "CDC NNDSS", sourceURL: "https://ndc.services.cdc.gov/conditions/hantavirus-infection/"),
        ReportableCondition(code: "37117007",  system: "SNOMED", display: "Legionellosis",                                     altNames: ["Legionnaires disease", "legionellosis", "Legionella pneumophila"],                                                      category: "respiratory",           source: "CDC NNDSS", sourceURL: "https://ndc.services.cdc.gov/conditions/legionellosis/"),
        ReportableCondition(code: "16814004",  system: "SNOMED", display: "Psittacosis",                                       altNames: ["psittacosis", "parrot fever", "Chlamydia psittaci infection"],                                                          category: "zoonotic",              source: "CDC NNDSS", sourceURL: "https://ndc.services.cdc.gov/conditions/psittacosis/"),
        ReportableCondition(code: "76783007",  system: "SNOMED", display: "Leptospirosis",                                     altNames: ["leptospirosis", "Weil disease", "Leptospira infection"],                                                                category: "zoonotic",              source: "CDC NNDSS", sourceURL: "https://ndc.services.cdc.gov/conditions/leptospirosis/"),
        ReportableCondition(code: "418182002", system: "SNOMED", display: "Marburg virus disease",                             altNames: ["Marburg", "Marburg hemorrhagic fever", "MHF"],                                                                          category: "outbreak_priority",     source: "WHO IDSR",  sourceURL: "https://www.afro.who.int/health-topics/viral-haemorrhagic-fevers"),
        ReportableCondition(code: "37109003",  system: "SNOMED", display: "Ebola virus disease",                               altNames: ["Ebola", "EVD", "Ebola hemorrhagic fever"],                                                                              category: "outbreak_priority",     source: "WHO IDSR",  sourceURL: "https://www.afro.who.int/health-topics/ebola-virus-disease"),
        ReportableCondition(code: "55735004",  system: "SNOMED", display: "Respiratory syncytial virus infection",             altNames: ["RSV", "RSV infection", "respiratory syncytial virus"],                                                                  category: "respiratory",           source: "CDC NNDSS", sourceURL: "https://ndc.services.cdc.gov/conditions/respiratory-syncytial-virus-infection/"),
        ReportableCondition(code: "442438000", system: "SNOMED", display: "Influenza-associated pediatric mortality",         altNames: ["pediatric flu death", "influenza pediatric mortality"],                                                                 category: "respiratory",           source: "CDC NNDSS", sourceURL: "https://ndc.services.cdc.gov/conditions/influenza-associated-pediatric-mortality/"),
        ReportableCondition(code: "240370005", system: "SNOMED", display: "MERS-CoV infection",                                altNames: ["MERS", "Middle East respiratory syndrome", "MERS-CoV"],                                                                  category: "respiratory",           source: "WHO IDSR",  sourceURL: "https://www.afro.who.int/health-topics/middle-east-respiratory-syndrome-coronavirus"),
        ReportableCondition(code: "60498001",  system: "SNOMED", display: "Cryptococcosis",                                    altNames: ["cryptococcosis", "Cryptococcus neoformans infection"],                                                                  category: "fungal",                source: "CDC NNDSS", sourceURL: "https://ndc.services.cdc.gov/conditions/cryptococcosis/"),
        ReportableCondition(code: "111407006", system: "SNOMED", display: "Hemolytic uremic syndrome",                         altNames: ["HUS", "hemolytic uremic syndrome", "Shiga toxin HUS"],                                                                  category: "outbreak_priority",     source: "CDC NNDSS", sourceURL: "https://ndc.services.cdc.gov/conditions/hemolytic-uremic-syndrome-post-diarrheal/"),
        ReportableCondition(code: "187192005", system: "SNOMED", display: "Cyclosporiasis",                                    altNames: ["cyclosporiasis", "Cyclospora cayetanensis infection"],                                                                  category: "foodborne",             source: "CDC NNDSS", sourceURL: "https://ndc.services.cdc.gov/conditions/cyclosporiasis/"),
        ReportableCondition(code: "21639007",  system: "SNOMED", display: "Vancomycin-resistant enterococci infection",        altNames: ["VRE", "vancomycin resistant enterococci"],                                                                              category: "healthcare_associated", source: "CDC NNDSS", sourceURL: "https://ndc.services.cdc.gov/conditions/vancomycin-resistant-enterococci/"),
        ReportableCondition(code: "73211009",  system: "SNOMED", display: "Diabetes mellitus",                                 altNames: ["diabetes mellitus", "DM", "diabetes"],                                                                                  category: "noncommunicable",       source: "WHO NCD",   sourceURL: "https://www.who.int/news-room/fact-sheets/detail/diabetes"),
        ReportableCondition(code: "38341003",  system: "SNOMED", display: "Hypertension",                                      altNames: ["hypertension", "high blood pressure", "HTN", "essential hypertension"],                                                 category: "noncommunicable",       source: "WHO NCD",   sourceURL: "https://www.who.int/news-room/fact-sheets/detail/hypertension"),
        ReportableCondition(code: "73442001",  system: "SNOMED", display: "Stevens-Johnson syndrome",                          altNames: ["Stevens-Johnson syndrome", "Stevens Johnson syndrome", "SJS"],                                                          category: "noncommunicable",       source: "Manual c20", sourceURL: "https://www.ncbi.nlm.nih.gov/books/NBK459323/"),
        ReportableCondition(code: "23067005",  system: "SNOMED", display: "Toxic epidermal necrolysis",                       altNames: ["toxic epidermal necrolysis", "Lyell syndrome", "Lyell-syndrome", "epidermal necrolysis"],                                category: "noncommunicable",       source: "Manual c20-r2", sourceURL: "https://www.ncbi.nlm.nih.gov/books/NBK557915/"),
        ReportableCondition(code: "770966009", system: "SNOMED", display: "Drug reaction with eosinophilia and systemic symptoms", altNames: ["drug reaction with eosinophilia and systemic symptoms", "DRESS", "DRESS syndrome", "drug-induced hypersensitivity syndrome"], category: "noncommunicable",  source: "Manual c20", sourceURL: "https://www.ncbi.nlm.nih.gov/books/NBK553107/"),
    ]
}
