// High-level Swift wrapper around LiteRT-LM's C-ABI shim.
//
// Usage:
//     let engine = try LiteRtLmEngine(modelPath: url, backend: .gpu)
//     let session = try engine.makeSession()
//     try session.prefill("Summarize this eICR: …")
//     for try await chunk in session.decode() {
//         print(chunk, terminator: "")
//     }
//
// Thread safety: mirror of the C++ API — one Engine can spawn multiple
// Sessions, but each Session is single-writer. We defer to the caller;
// the wrapper does NOT introduce its own locks.

import Foundation
// The LiteRtLmCore xcframework ships its own umbrella header +
// module.modulemap generated by Bazel; Swift imports the C symbols from
// there directly, so no separate C shim target is needed.
@_implementationOnly import LiteRtLmCore

public enum LiteRtLmBackend: Int32 {
    case cpu = 0
    case gpu = 1
    case npu = 2
}

public enum LiteRtLmError: Error, CustomStringConvertible {
    case engineCreateFailed(path: String)
    case sessionCreateFailed
    case prefillFailed(code: Int32)
    case decodeFailed(code: Int32)

    public var description: String {
        switch self {
        case .engineCreateFailed(let path):
            return "LiteRtLmEngine: failed to load model at \(path)"
        case .sessionCreateFailed:
            return "LiteRtLmEngine: failed to create session"
        case .prefillFailed(let c):
            return "LiteRtLmSession: prefill failed (code \(c))"
        case .decodeFailed(let c):
            return "LiteRtLmSession: decode failed (code \(c))"
        }
    }
}

/// Returns the version string exposed by the C shim. Useful for smoke
/// tests that only need to confirm the xcframework is linked.
public func liteRtLmShimVersion() -> String {
    return String(cString: litertlm_shim_version())
}

// The forward-declared opaque C structs (`LiteRtLmEngineOpaque`,
// `LiteRtLmSessionOpaque`) are imported by the Swift compiler as
// `OpaquePointer`. Use them directly.
private typealias EngineRef = OpaquePointer
private typealias SessionRef = OpaquePointer

/// An on-device LLM engine backed by LiteRT-LM. Wraps a single model file;
/// thread-safe to share across sessions. `@unchecked Sendable` because the
/// wrapped C pointer is immutable-after-init and the upstream Engine is
/// documented as safe to share across sessions.
public final class LiteRtLmEngine: @unchecked Sendable {
    fileprivate let raw: EngineRef

    public init(modelPath: URL, backend: LiteRtLmBackend = .gpu) throws {
        let path = modelPath.path
        guard let p = (path.withCString { cpath in
            litertlm_engine_create(cpath, backend.rawValue)
        }) else {
            throw LiteRtLmError.engineCreateFailed(path: path)
        }
        self.raw = p
    }

    deinit {
        litertlm_engine_destroy(raw)
    }

    public func makeSession() throws -> LiteRtLmSession {
        guard let p = litertlm_session_create(raw) else {
            throw LiteRtLmError.sessionCreateFailed
        }
        return LiteRtLmSession(raw: p, engine: self)
    }
}

/// A single conversational turn with the engine. Keeps a strong reference
/// to the owning `LiteRtLmEngine` to prevent the native pointer from being
/// torn down while this session is alive.
///
/// Marked `@unchecked Sendable` so the decode() AsyncStream can run on a
/// detached task. Callers MUST NOT invoke prefill/decode from two threads
/// concurrently — mirror of the C++ Session's single-writer contract.
public final class LiteRtLmSession: @unchecked Sendable {
    fileprivate let raw: SessionRef
    private let engine: LiteRtLmEngine

    fileprivate init(raw: SessionRef, engine: LiteRtLmEngine) {
        self.raw = raw
        self.engine = engine
    }

    deinit {
        litertlm_session_destroy(raw)
    }

    public func prefill(_ prompt: String) throws {
        let rc = prompt.withCString { cstr in
            litertlm_session_prefill(raw, cstr)
        }
        if rc != 0 { throw LiteRtLmError.prefillFailed(code: rc) }
    }

    /// Streaming decode. Returns an `AsyncThrowingStream` that yields UTF-8
    /// substrings as the model emits them. Calls `decode_step` on a
    /// background task; closes the stream on EOS or error.
    ///
    /// The detached task strongly retains `self`, so the underlying native
    /// session pointer cannot be torn down mid-decode even if the Swift
    /// caller drops its reference to the `LiteRtLmSession`.
    public func decode(bufferSize: Int = 512) -> AsyncThrowingStream<String, Error> {
        return AsyncThrowingStream { continuation in
            let owner = self  // strong retain for the duration of the task
            let task = Task.detached(priority: .userInitiated) {
                var scratch = [CChar](repeating: 0, count: bufferSize)
                while !Task.isCancelled {
                    let written = scratch.withUnsafeMutableBufferPointer { buf -> Int32 in
                        litertlm_session_decode_step(
                            owner.raw,
                            buf.baseAddress,
                            Int32(bufferSize)
                        )
                    }
                    if written < 0 {
                        continuation.finish(throwing: LiteRtLmError.decodeFailed(code: written))
                        return
                    }
                    if written == 0 {
                        continuation.finish()
                        return
                    }
                    let data = Data(bytes: scratch, count: Int(written))
                    if let s = String(data: data, encoding: .utf8) {
                        continuation.yield(s)
                    }
                }
                continuation.finish()
            }
            continuation.onTermination = { _ in task.cancel() }
        }
    }
}
